.TH "Cryptify.Properties" 3 "Version 1.0.0" "Cryptify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cryptify.Properties
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "A strongly-typed resource class, for looking up localized strings, etc\&. "
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cryptify from the source code\&.
