.TH "Cryptify.Main" 3 "Version 1.0.0" "Cryptify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cryptify.Main
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void Cryptify\&.Main\&.Dispose (bool disposing)\fR [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cryptify from the source code\&.
