.TH "dES" 3 "Version 1.0.0" "Cryptify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dES
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIEncryptionAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBEncrypt\fP (string Content, byte[] Key)"
.br
.ti -1c
.RI "string \fBDecrypt\fP (string Content, byte[] Key)"
.br
.in -1c

Public Member Functions inherited from \fBIEncryptionAlgorithm\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBIEncryptionAlgorithm\fP
.SH "Member Function Documentation"
.PP 
.SS "string dES\&.Decrypt (string Content, byte[] Key)"

.PP
Implements \fBIEncryptionAlgorithm\fP\&.
.SS "string dES\&.Encrypt (string Content, byte[] Key)"

.PP
Implements \fBIEncryptionAlgorithm\fP\&.
.SH "Property Documentation"
.PP 
.SS "string dES\&.Name\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBIEncryptionAlgorithm\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cryptify from the source code\&.
