.TH "Engine" 3 "Version 1.0.0" "Cryptify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEngine\fP (\fBIEncryptionAlgorithm\fP _Algorithm)"
.br
.ti -1c
.RI "void \fBProcess\fP (string Content, string Password, bool Decrypting)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIEncryptionAlgorithm\fP \fBAlgorithm\fP\fR [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cryptify from the source code\&.
