.TH "IEncryptionAlgorithm" 3 "Version 1.0.0" "Cryptify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEncryptionAlgorithm
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAES\fP, \fBTripledES\fP, and \fBdES\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBEncrypt\fP (string Content, byte[] Key)"
.br
.ti -1c
.RI "string \fBDecrypt\fP (string Content, byte[] Key)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cryptify from the source code\&.
