.TH "Cryptify" 3 "Version 1.0.0" "Cryptify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cryptify
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMain\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cryptify from the source code\&.
